ASSETS: dict[str, dict[str, dict[str, str]]] = {
    "💱 Forex": {
        "EUR/USD":  {"yf": "EURUSD=X",  "tv": "FX:EURUSD"},
        "GBP/USD":  {"yf": "GBPUSD=X",  "tv": "FX:GBPUSD"},
        "USD/JPY":  {"yf": "JPY=X",     "tv": "FX:USDJPY"},
        "USD/CHF":  {"yf": "CHF=X",     "tv": "FX:USDCHF"},
        "AUD/USD":  {"yf": "AUDUSD=X",  "tv": "FX:AUDUSD"},
        "USD/CAD":  {"yf": "CAD=X",     "tv": "FX:USDCAD"},
        "NZD/USD":  {"yf": "NZDUSD=X",  "tv": "FX:NZDUSD"},
        "EUR/GBP":  {"yf": "EURGBP=X",  "tv": "FX:EURGBP"},
        "EUR/JPY":  {"yf": "EURJPY=X",  "tv": "FX:EURJPY"},
        "GBP/JPY":  {"yf": "GBPJPY=X",  "tv": "FX:GBPJPY"},
        "AUD/JPY":  {"yf": "AUDJPY=X",  "tv": "FX:AUDJPY"},
    },
    "📊 Índices Globais": {
        "S&P 500":         {"yf": "^GSPC",  "tv": "CAPITALCOM:US500"},
        "Nasdaq 100":      {"yf": "^IXIC",  "tv": "CAPITALCOM:US100"},
        "Dow Jones (DJI)": {"yf": "^DJI",   "tv": "CAPITALCOM:US30"},
        "Russell 2000":    {"yf": "^RUT",   "tv": "CAPITALCOM:US2000"},
        "DAX 40":          {"yf": "^GDAXI", "tv": "CAPITALCOM:DE40"},
        "FTSE 100":        {"yf": "^FTSE",  "tv": "CAPITALCOM:UK100"},
        "Nikkei 225":      {"yf": "^N225",  "tv": "CAPITALCOM:JP225"},
        "VIX":             {"yf": "^VIX",   "tv": "TVC:VIX"},
    },
    "🏆 Commodities": {
        "Ouro":          {"yf": "GC=F", "tv": "TVC:GOLD"},
        "Prata":         {"yf": "SI=F", "tv": "TVC:SILVER"},
        "Platina":       {"yf": "PL=F", "tv": "TVC:PLATINUM"},
        "Cobre":         {"yf": "HG=F", "tv": "CAPITALCOM:COPPER"},
        "Petróleo WTI":  {"yf": "CL=F", "tv": "TVC:USOIL"},
        "Petróleo Brent":{"yf": "BZ=F", "tv": "TVC:UKOIL"},
        "Gás Natural":   {"yf": "NG=F", "tv": "TVC:NATGAS"},
        "Milho":         {"yf": "ZC=F", "tv": "CAPITALCOM:CORN"},
        "Trigo":         {"yf": "ZW=F", "tv": "CAPITALCOM:WHEAT"},
        "Café":          {"yf": "KC=F", "tv": "CAPITALCOM:COFFEE"},
    },
    "₿ Cripto": {
        "Bitcoin":        {"yf": "BTC-USD",  "tv": "BINANCE:BTCUSDT"},
        "Ethereum":       {"yf": "ETH-USD",  "tv": "BINANCE:ETHUSDT"},
        "Solana":         {"yf": "SOL-USD",  "tv": "BINANCE:SOLUSDT"},
        "Binance Coin":   {"yf": "BNB-USD",  "tv": "BINANCE:BNBUSDT"},
        "XRP":            {"yf": "XRP-USD",  "tv": "BINANCE:XRPUSDT"},
        "Cardano":        {"yf": "ADA-USD",  "tv": "BINANCE:ADAUSDT"},
        "Dogecoin":       {"yf": "DOGE-USD", "tv": "BINANCE:DOGEUSDT"},
        "Polkadot":       {"yf": "DOT-USD",  "tv": "BINANCE:DOTUSDT"},
        "Chainlink":      {"yf": "LINK-USD", "tv": "BINANCE:LINKUSDT"},
        "Avalanche":      {"yf": "AVAX-USD", "tv": "BINANCE:AVAXUSDT"},
    },
    "🍎 Ações (Blue Chips)": {
        "Apple":               {"yf": "AAPL",  "tv": "NASDAQ:AAPL"},
        "Microsoft":           {"yf": "MSFT",  "tv": "NASDAQ:MSFT"},
        "Nvidia":              {"yf": "NVDA",  "tv": "NASDAQ:NVDA"},
        "Tesla":               {"yf": "TSLA",  "tv": "NASDAQ:TSLA"},
        "Amazon":              {"yf": "AMZN",  "tv": "NASDAQ:AMZN"},
        "Alphabet (Google)":   {"yf": "GOOGL", "tv": "NASDAQ:GOOGL"},
        "Meta (Facebook)":     {"yf": "META",  "tv": "NASDAQ:META"},
        "JPMorgan":            {"yf": "JPM",   "tv": "NYSE:JPM"},
        "Visa":                {"yf": "V",     "tv": "NYSE:V"},
        "Berkshire Hathaway":  {"yf": "BRK-B", "tv": "NYSE:BRK.B"},
    },
}
